### ISSUE TITLE
[Bug] Gold Nuggets randomly have way too large energy value

### ISSUE THREAD

**Issue by programmerjake** [ThePython10110/ExchangeClone#14]
**Describe the bug**
A Gold Nugget randomly has a waay too large energy value (16,384). A Gold Ingot's energy value isn't affected.
I've also seen this happen with Iron Nuggets (though, for iron, not yet in the latest version, so that may be fixed), and with Carbon Steel.

**Expected behavior**
Gold Nuggets have 1/9th the energy of Gold Ingots.

**Game (e.g. Minetest Game)**
MineClone2 with latest versions of Technic Plus Beta and ExchangeClone.

**Screenshots**
Bad Gold Nugget energy:
![screenshot_20240110_191450](https://github.com/ThePython10110/ExchangeClone/assets/4584340/c06fd136-9136-465e-9b2c-c338f74c0510)
Bad Carbon Steel energy:
![screenshot_20240110_192116](https://github.com/ThePython10110/ExchangeClone/assets/4584340/72e29383-4f03-4e51-abf4-7799a469ae96)

**Additional context**
[Previous discussion](https://github.com/ThePython10110/ExchangeClone/issues/13#issuecomment-1884316449)

**Comment by programmerjake** [comment]
as mentioned previously, if it doesn't show up, restart the world 3-4 times, it is randomly chosen at world startup.

**Comment by ThePython10110** [comment]
The gold is caused by a similar thing as the iron: I left gold ingots to be automatically calculated, since I didn't think there was any way to make gold nuggets without the ingots... but I forgot about gold horse armor. So I fixed that.

The issue with the carbon steel is actually a problem with Technic where you can grind one iron nugget down into two iron dust. ExchangeClone sometimes notices this and sets the energy value accordingly, but sometimes doesn't (depends on whether iron dust's energy value is registered before or after iron nuggets). I'm going to report this in the Technic repo right now.
